Console.WriteLine("Programm to find strike rate");
Console.WriteLine("Enter the number of balls");
int balls=Convert.ToInt16(Console.ReadLine());
Console.WriteLine("enter the runs");
int runs=Convert.ToInt32(Console.ReadLine());
decimal strikerate=(decimal)runs/balls*100;
Console.WriteLine("Strike rate is "+strikerate);
Console.WriteLine("your strike rate programs ends here");
Console.WriteLine("Program to generate the mad libs");
Console.WriteLine("Enter Exclaimation expression");
string exclaimation=Console.ReadLine();
Console.WriteLine(exclaimation);
Console.WriteLine("Enter adverb");
string adverb=Console.ReadLine();
Console.WriteLine(adverb);
Console.WriteLine("Enter noun");
string noun=Console.ReadLine();
Console.WriteLine(noun);
Console.WriteLine("Enter adjective");
string adjective=Console.ReadLine();
Console.WriteLine(adjective);
Console.WriteLine("final mad libs sentence generated");
Console.WriteLine($"{exclaimation} ! he/she {adverb} as he/she jumped into his/her {noun} and drove off with his/her {adjective} wife/husband");